openapi: 3.1.0
info:
  title: "Project Management API"
  version: "0.1.0"
  description: "This is a CRUD API built with Node.js and Express accessing a MongoDB backend."
  license:
    name: "NO LICENSE - DEMO PROJECT FOR EDP"
    url: "https://www.google.com"
  contact:
    name: "Craig O'Loughlin / Zachary Mowry"
    url: "https://www.travelers.com"
    email: "coloughl@travelers.com"
servers:
  - url: "http://localhost:3500"
paths:
  /projects:
    get:
      summary: "Retrieve all projects"
      responses:
        '200':
          description: "A list of projects"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      summary: "Create a new project"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: "Project created successfully"
        '400':
          description: "Bad request"
  /projects/{id}:
    get:
      summary: "Get a project by ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Project retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: "Project not found"
    put:
      summary: "Update a project by ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: "Project updated successfully"
        '404':
          description: "Project not found"
    delete:
      summary: "Delete a project by ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Project deleted successfully"
        '404':
          description: "Project not found"
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          description: "Unique identifier for the project"
        name:
          type: string
          description: "Name of the project"
        description:
          type: string
          description: "Description of the project"
        status:
          type: string
          description: "Current status of the project"
        createdAt:
          type: string
          format: date-time
          description: "Creation timestamp"
        updatedAt:
          type: string
          format: date-time
          description: "Last update timestamp"
      required:
        - name
        - status
